site_name: VQASynth Documentation
nav:
- Home: index.md
- Application Documentation: application-documentation.md
theme:
  name: rtd-dropdown
markdown_extensions:
- toc:
    permalink: true
plugins:
  - search