#!/bin/bash
set -euo pipefail

# Define directories using VQASynth's /data convention
DATA_ROOT=${DATA_ROOT:-/data}
RAW_INPUT_DIR="$DATA_ROOT/input"
FINAL_OUTPUT_DIR="$DATA_ROOT/output"
export CONFIG_DIR=${CONFIG_DIR:-$DATA_ROOT/config}

# Intermediate directory for multi-step processing
INTERMEDIATE_DIR="$DATA_ROOT/intermediate_metadata_deid"
mkdir -p "$RAW_INPUT_DIR" "$FINAL_OUTPUT_DIR" "$CONFIG_DIR" "$INTERMEDIATE_DIR"

echo "================================================="
echo "VQASynth - DICOM De-identification Stage"
echo "================================================="
echo "Input DICOMs: $RAW_INPUT_DIR"
echo "Output DICOMs: $FINAL_OUTPUT_DIR"
echo "Config: $CONFIG_DIR"
echo "-------------------------------------------------"

# Create placeholder config files if they don't exist, as the scripts expect them.
ID_MAP_FILE="$CONFIG_DIR/patient_id_mapping.csv"
SHIFT_CSV_FILE="$CONFIG_DIR/shift.csv"

if [ ! -s "$ID_MAP_FILE" ]; then
    echo "INFO: Config file not found. Creating placeholder: $ID_MAP_FILE"
    echo "original_id,new_id" > "$ID_MAP_FILE"
    echo "PAT001,000001" >> "$ID_MAP_FILE" # Example entry
fi

if [ ! -s "$SHIFT_CSV_FILE" ]; then
    echo "INFO: Config file not found. Creating placeholder: $SHIFT_CSV_FILE"
    echo "PatientID,offset" > "$SHIFT_CSV_FILE"
    echo "000001,365" >> "$SHIFT_CSV_FILE" # Example entry
fi

# Step 1: Run metadata de-identification
echo "Step 1: Processing DICOM metadata..."
export INPUT_DIR="$RAW_INPUT_DIR"
export OUTPUT_DIR="$INTERMEDIATE_DIR"
# CONFIG_DIR is already exported
python /app/deidentify_metadata.py

# Check if metadata step produced output
if [ -z "$(ls -A $INTERMEDIATE_DIR)" ]; then
   echo "Error: Metadata de-identification failed. No files were produced." >&2
   exit 1
fi
echo "Metadata processing complete. Intermediate files in $INTERMEDIATE_DIR"

# Step 2: Run pixel data (burned-in text) redaction on the metadata-cleaned files
echo "Step 2: Processing pixel data for burned-in text..."
export INPUT_DIR="$INTERMEDIATE_DIR"
export OUTPUT_DIR="$FINAL_OUTPUT_DIR"
# CONFIG_DIR is still exported but not used by redact_pixel_data.py
python /app/redact_pixel_data.py

# Step 3: Copy over config and mapping files to output for traceability
cp "$CONFIG_DIR"/*.csv "$FINAL_OUTPUT_DIR/" 2>/dev/null || true # Allow failure if no csv
# The uid_mapping.csv is generated by the metadata script in its output dir
cp "$INTERMEDIATE_DIR"/uid_mapping.csv "$FINAL_OUTPUT_DIR/" 2>/dev/null || true

echo "-------------------------------------------------"
echo "De-identification complete. Final output is in $FINAL_OUTPUT_DIR"
echo "================================================="